### ISSUE TITLE
Requests and bugs(2)

### ISSUE THREAD

**Issue by xkcdjerry** [uuk0/mcpython-4#4]
(I can help)
Request:Make a proper interface, not just the text version
BUG:When I use lone "/give", it gives this error message:
![image](https://user-images.githubusercontent.com/49294431/64845995-129b6100-d63e-11e9-87ee-d68108f8e576.png)
text version:
exceptions during calling event named user:keyboard:press:
callen over:
exceptions:
  File "C:/Users/MyName/Desktop/mcpython-4-master/__main__.py", line 91, in <module>
    main()
  File "C:/Users/MyName/Desktop/mcpython-4-master/__main__.py", line 82, in main
    run()
  File "C:/Users/MyName/Desktop/mcpython-4-master/__main__.py", line 72, in run
    pyglet.app.run()
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python37\lib\site-packages\pyglet\app\__init__.py", line 142, in run
    event_loop.run()
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python37\lib\site-packages\pyglet\app\base.py", line 175, in run
    self._run()
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python37\lib\site-packages\pyglet\app\base.py", line 188, in _run
    platform_event_loop.step(timeout)
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python37\lib\site-packages\pyglet\app\win32.py", line 123, in step
    _user32.DispatchMessageW(ctypes.byref(msg))
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python37\lib\site-packages\pyglet\window\win32\__init__.py", line 640, in f
    result = event_handler(msg, wParam, lParam)
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python37\lib\site-packages\pyglet\window\win32\__init__.py", line 711, in _event_key
    self.dispatch_event(ev, symbol, modifiers)
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python37\lib\site-packages\pyglet\window\__init__.py", line 1313, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python37\lib\site-packages\pyglet\event.py", line 370, in dispatch_event
    if handler(*args):
  File "C:\Users\MyName\Desktop\mcpython-4-master\rendering\window.py", line 265, in on_key_press
    G.eventhandler.call("user:keyboard:press", symbol, modifiers)
  File "C:\Users\MyName\Desktop\mcpython-4-master\event\EventHandler.py", line 94, in call
    traceback.print_stack()
Traceback (most recent call last):
  File "C:\Users\MyName\Desktop\mcpython-4-master\event\EventHandler.py", line 90, in call
    function(*args, **kwargs)
  File "C:\Users\MyName\Desktop\mcpython-4-master\chat\Chat.py", line 88, in on_key_press
    G.commandparser.parse(self.text)
  File "C:\Users\MyName\Desktop\mcpython-4-master\chat\command\CommandParser.py", line 59, in parse
    command.parse(values, trace, info)
  File "C:\Users\MyName\Desktop\mcpython-4-master\chat\command\CommandGive.py", line 28, in parse
    stack = gui.ItemStack.ItemStack(values[1])  # get the stack to add
IndexError: list index out of range

Maybe it can handle the exception in a more graceful way?

**Comment by uuk0** [comment]
It should be automaticly detected and explained to the user.
May be an bug in the chat/command/CommandParser.

**Comment by uuk0** [comment]
found the bug & fixed it. will be comitted soon
